import type { Metadata } from "next";
import "./globals.css";
import { publicSans } from "./ui/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.className} antialiased min-h-dvh bg-beige-100`}
      >
        {children}
      </body>
    </html>
  );
}
